#include "cpu_state.h"
#include "recompiled_functions.h" // Use the header generated by the recompiler
#include "syscalls.h"
#include "memory.h"
#include <iostream>
#include <iomanip>
#include <fstream>
#include <filesystem>
#include <cstring>

// Global log file stream to be used by the host and recompiled functions
std::ofstream g_logFile;

void init_cpu_context(CpuContext& ctx) {
    memset(&ctx, 0, sizeof(CpuContext));
    
    // Set the entry point (you'll need to get this from the ELF)
    ctx.cpuRegs.pc = 0x100008; // Example starting PC
    
    // Initialize stack pointer to end of main RAM
    // PS2 typically uses the top of main RAM for the stack
    ctx.cpuRegs.GPR.r[29].UD[0] = 0x01FFFF00; // Near end of 32MB main RAM
    
    // Alternative: Use scratchpad for stack (some games do this)
    // ctx.cpuRegs.GPR.r[29].UD[0] = 0x70003FF0; // Near end of scratchpad
    
    // Initialize other important registers
    ctx.cpuRegs.GPR.r[28].UD[0] = 0; // Global pointer (gp)
    ctx.cpuRegs.GPR.r[30].UD[0] = 0; // Frame pointer (fp)
}

// A simple execution loop
void execute_recompiled_code(CpuContext& ctx) {
    // This is a basic loop. A more advanced implementation would handle interrupts
    // and other complexities of the PS2's execution flow.
    while (true) {
        // Find the function pointer for the current PC
        auto it = recompiled_functions.find(ctx.cpuRegs.pc);
        if (it != recompiled_functions.end()) {
            // Log to both console and file for visibility
            std::cout << "Executing function at PC: 0x" << std::hex << ctx.cpuRegs.pc << std::endl;
            g_logFile << "Executing function at PC: 0x" << std::hex << ctx.cpuRegs.pc << std::endl;

            it->second(ctx); // Execute the recompiled block
        } else {
            std::cerr << "Error: No recompiled function found for PC 0x"
                      << std::hex << ctx.cpuRegs.pc << std::endl;
            g_logFile << "Error: No recompiled function found for PC 0x"
                      << std::hex << ctx.cpuRegs.pc << std::endl;
            break; // Halt execution
        }

        // A simple way to stop execution for now.
        // You'll want to replace this with a proper exit syscall.
        if (ctx.cpuRegs.pc == 0) {
            break;
        }
    }
}

int main() {
    // Create a "logs" directory if it doesn't already exist
    if (!std::filesystem::exists("logs")) {
        std::filesystem::create_directory("logs");
    }

    // Open the log file for writing
    g_logFile.open("logs/runtime_log.txt");
    if (!g_logFile.is_open()) {
        std::cerr << "Fatal Error: Could not open log file for writing." << std::endl;
        return 1;
    }

    std::cout << "Starting the host application... Logging to logs/runtime_log.txt" << std::endl;
    g_logFile << "Starting the host application..." << std::endl;

    // Initialize the CPU state.
    CpuContext ctx;
    init_cpu_context(ctx);

    // This map is defined in recompiled_functions.cpp and holds pointers
    // to all your recompiled functions.
    initialize_recompiled_functions(); 

    std::cout << "Executing recompiled code..." << std::endl;
    g_logFile << "Executing recompiled code..." << std::endl;
    execute_recompiled_code(ctx);

    std::cout << "Host application finished." << std::endl;
    g_logFile << "Host application finished." << std::endl;
    
    g_logFile.close();
    return 0;
}