#include "cpu_state.h"
#include "recompiled_functions.h" // Use the header generated by the recompiler
#include "syscalls.h"
#include <iostream>

// A simple execution loop
void execute_recompiled_code(CpuState& ctx) {
    // This is a basic loop. A more advanced implementation would handle interrupts
    // and other complexities of the PS2's execution flow.
    while (true) {
        // Find the function pointer for the current PC
        auto it = recompiled_functions.find(ctx.pc);
        if (it != recompiled_functions.end()) {
            it->second(ctx); // Execute the recompiled block
        } else {
            std::cerr << "Error: No recompiled function found for PC 0x"
                      << std::hex << ctx.pc << std::endl;
            break; // Halt execution
        }

        // A simple way to stop execution for now.
        // You'll want to replace this with a proper exit syscall.
        if (ctx.pc == 0) {
            break;
        }
    }
}

int main() {
    std::cout << "Starting the host application..." << std::endl;

    // Initialize the CPU state.
    CpuState ctx;
    init_cpu_context(ctx);

    // This map is defined in recompiled_functions.cpp and holds pointers
    // to all your recompiled functions.
    initialize_recompiled_functions(); 

    std::cout << "Executing recompiled code..." << std::endl;
    execute_recompiled_code(ctx);

    std::cout << "Host application finished." << std::endl;
    return 0;
}